package serwer;
import javax.swing.*;
import program.*;

public class DanePolaczenia extends javax.swing.JDialog {
    private boolean anulowal=false; // użytkownik znulował
    
    public DanePolaczenia(OknoProgramu r) {//java.awt.Window
        initComponents();
        setSize(370,220);
        setLocationRelativeTo(r);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPort = new javax.swing.JTextField();
        jOpis = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jCzas = new javax.swing.JTextField();

        getContentPane().setLayout(null);

        setTitle("Informacje o serwerze");
        setModal(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jLabel1.setText("numer portu:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 20, 110, 16);

        jLabel2.setText("Napisz Kilka zdan o sobie");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 90, 150, 16);

        jPort.setColumns(6);
        jPort.setText("6667");
        getContentPane().add(jPort);
        jPort.setBounds(150, 20, 70, 20);

        jOpis.setColumns(30);
        jOpis.setRows(3);
        getContentPane().add(jOpis);
        jOpis.setBounds(20, 110, 330, 48);

        jButton1.setMnemonic('O');
        jButton1.setText("Ok");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        getContentPane().add(jButton1);
        jButton1.setBounds(250, 20, 89, 26);

        jButton2.setMnemonic('a');
        jButton2.setText("Anuluj");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        getContentPane().add(jButton2);
        jButton2.setBounds(250, 60, 90, 26);

        jLabel4.setText("\u0142aczny czas gry:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 50, 120, 16);

        jCzas.setText("15");
        getContentPane().add(jCzas);
        jCzas.setBounds(150, 50, 50, 20);

        pack();
    }//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        anulowal = true;
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed
    
    public boolean isAnulowano() {
        return anulowal;
    }
    
    public int getPort() {
        try {
            return Integer.parseInt(jPort.getText());
        } catch (NumberFormatException e) {
            return -1;
        }
    }
    
    public int getCzasGry() {
        try {
            return Integer.parseInt(jCzas.getText());
        } catch (NumberFormatException e) {
            return -1;
        }
    }
    
    public String getOpis() {
        return jOpis.getText();
    }
    
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JTextField jCzas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextArea jOpis;
    private javax.swing.JTextField jPort;
    // End of variables declaration//GEN-END:variables
    
}