
package figury;
import java.awt.*;
import javax.swing.*;
import program.*;

public abstract class Figura extends javax.swing.JPanel {    
    protected boolean biale;    
    protected char id;          
    protected ImageIcon obrazek;
    

    public Figura() {
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents

        setLayout(null);

    }//GEN-END:initComponents

    public void paint(java.awt.Graphics graphics) {
        obrazek.paintIcon(this, graphics, 0, 0);
    }
    
    public void paintxy(int x, int y, java.awt.Graphics graphics) {
        if (obrazek != null)
            obrazek.paintIcon(this, graphics, x, y);
    }
    
    public abstract int zbadajRuch(Point p1, Point p2, Figura[][] f, Szachownica sz);
    public abstract int zbadajRuchBezKrola(Point p1, Point p2, Figura[][] f);
    public boolean isBiala() {
        return biale;
    }
    
    protected boolean testujSzachowanie(Point p1, Point p2, Figura[][] f, Szachownica sz) {
        if (f[p1.x][p1.y] instanceof Krol) sz.setKrol(biale, p2); 
        Figura temp = f[p2.x][p2.y];
        f[p2.x][p2.y] = f[p1.x][p1.y]; 
        f[p1.x][p1.y] = null; 
        boolean czySzach = sz.szachowanieKrola(biale);
        f[p1.x][p1.y] = f[p2.x][p2.y]; 
        f[p2.x][p2.y] = temp;
        if (f[p1.x][p1.y] instanceof Krol) sz.setKrol(biale, p1);
        return czySzach;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}