
package klient;
import javax.swing.*;
import java.net.*;

public class DanePrzeciwnika extends javax.swing.JDialog {
    private boolean anulowal=true;
    
    /** Creates new form DanePolaczenia */
    public DanePrzeciwnika(JFrame r) {
        wspolneKonstruktora(r);
    }
    public DanePrzeciwnika(JFrame r, InetAddress ip, int czas, String info) {
        wspolneKonstruktora(r);
        jIP.setText(ip.getHostName());
        jCzas.setText(String.valueOf(czas));
        jOpis.setText(info);
        
    }
    private void wspolneKonstruktora(JFrame r) {
        initComponents();
        setSize(370,215);
        setLocationRelativeTo(r);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jIP = new javax.swing.JTextField();
        jOpis = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jCzas = new javax.swing.JTextField();

        getContentPane().setLayout(null);

        setTitle("Czy zgadzasz si\u0119 na t\u0119 gr\u0119?");
        setModal(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Adres IP gracza");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 20, 130, 16);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Opis:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 80, 29, 16);

        jIP.setColumns(6);
        jIP.setEditable(false);
        jIP.setText("127.0.0.1");
        getContentPane().add(jIP);
        jIP.setBounds(170, 20, 100, 20);

        jOpis.setColumns(30);
        jOpis.setEditable(false);
        jOpis.setForeground(new java.awt.Color(255, 255, 255));
        jOpis.setLineWrap(true);
        jOpis.setRows(3);
        jOpis.setOpaque(false);
        getContentPane().add(jOpis);
        jOpis.setBounds(20, 100, 360, 48);

        jButton1.setMnemonic('Z');
        jButton1.setText("Zagraj");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        getContentPane().add(jButton1);
        jButton1.setBounds(290, 50, 100, 26);

        jButton2.setMnemonic('O');
        jButton2.setText("Odrzu\u0107");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        getContentPane().add(jButton2);
        jButton2.setBounds(290, 20, 100, 26);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("\u0142\u0105czny czas gry:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 50, 130, 16);

        jCzas.setEditable(false);
        jCzas.setText("15");
        getContentPane().add(jCzas);
        jCzas.setBounds(170, 50, 100, 20);

    }//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        anulowal = false;
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed
    
    public boolean isAnulowano() {
        return anulowal;
    }
           
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JTextField jCzas;
    private javax.swing.JTextField jIP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextArea jOpis;
    // End of variables declaration//GEN-END:variables
    
}