package program;
import javax.swing.*;
import javax.swing.border.*;
import java.io.*;
import java.net.*;
import serwer.*;
import klient.*;
import klientserwer.*;
import figury.*;

public class OknoProgramu extends javax.swing.JFrame {
    private Border ramka = new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0));
    private Serwer serwer;
    public Gra gra;
    private NowaGra ng;
    
    /** Creates new form OknoProgramu */
    public OknoProgramu() {
        initComponents();
        zaznaczZmianeGracza(true);
        ng = new NowaGra(this); 
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jKolor = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        szachownica1 = new program.Szachownica();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();

        getContentPane().setLayout(new java.awt.GridBagLayout());

        setTitle("Szachy wer. 0.1");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel1.setEnabled(false);
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Kolor gracza.");
        jPanel2.add(jLabel1, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        jPanel2.add(jKolor, gridBagConstraints);

        jPanel1.add(jPanel2, new java.awt.GridBagConstraints());

        jPanel3.setLayout(new java.awt.GridBagLayout());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(jPanel3, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        jPanel1.add(jPanel4, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(jPanel1, gridBagConstraints);

        szachownica1.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(szachownica1, gridBagConstraints);

        jMenu1.setMnemonic('g');
        jMenu1.setText("Gra");
        jMenuItem1.setMnemonic('n');
        jMenuItem1.setText("Nowa");
        jMenuItem1.setToolTipText("Zaczyna nas\u0142uchiwa\u0107 po\u0142\u0105cze\u0144 od innych graczy");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });

        jMenu1.add(jMenuItem1);

        jMenuItem2.setMnemonic('p');
        jMenuItem2.setText("Poddaj\u0119 si\u0119");
        jMenuItem2.setToolTipText("Pr\u00f3buje po\u0142\u0105czy\u0107 si\u0119 z graczem czekaj\u0105cym na po\u0142\u0105czenie");
        jMenuItem2.setEnabled(false);
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });

        jMenu1.add(jMenuItem2);

        jMenu1.add(jSeparator1);

        jMenuItem3.setMnemonic('k');
        jMenuItem3.setText("Koniec");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });

        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setMnemonic('o');
        jMenu2.setText("Opcje");
        jMenuItem4.setMnemonic('p');
        jMenuItem4.setText("Poka\u017c czas oczekiwania");
        jMenuItem4.setToolTipText("Jak d\u0142ugo czekamy na jakiego\u015b przeciwnika");
        jMenuItem4.setEnabled(false);
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });

        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        jMenu3.setMnemonic('p');
        jMenu3.setText("Pomoc");
        jMenuItem5.setMnemonic('o');
        jMenuItem5.setText("O programie");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });

        jMenu3.add(jMenuItem5);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }//GEN-END:initComponents

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        new OProgramie(this, true).show();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        if (gra!=null) gra.chceSiePoddac();
        System.exit(0);
    }//GEN-LAST:event_jMenuItem3ActionPerformed
                   

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        if (gra!=null) gra.chceSiePoddac();        
    }//GEN-LAST:event_jMenuItem2ActionPerformed
    
    // użytkownik chce zobaczyć jak długo już działa jego serwer;
    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        if (serwer != null) serwer.pokazZegar();
    }//GEN-LAST:event_jMenuItem4ActionPerformed
    public void setSerwer(Serwer serwer) {
        this.serwer = serwer;
    }
    
    public Serwer getSerwer() {
        return serwer;
    }
    public void menuZegar(boolean stan) {
        jMenuItem4.setEnabled(stan);
    }
    
    public void menuPoddajeSie(boolean stan) {
        jMenuItem2.setEnabled(stan);
    }

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        ng.setLocationRelativeTo(this);
        ng.setSize(300,200);
        ng.show();
    }//GEN-LAST:event_jMenuItem1ActionPerformed
    public Szachownica getSzachownica() {
        return szachownica1;
    }
       
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new OknoProgramu().show();
    }
        
    public void zaznaczZmianeGracza(boolean isBiale) {
        /*if (isBiale) {
            jGracz1.setBorder(ramka);
            jGracz2.setBorder(null);
        } else {
            jGracz1.setBorder(null);
            jGracz2.setBorder(ramka);
        }*/
        jKolor.setIcon(Pionek.getObrazek(isBiale));
    }
    
    public void zmienCzas(String lan, boolean biale) {
        //if (biale) jCzas1.setText(lan);
        //else jCzas2.setText(lan);
    }
    
    public void zeruj() {
        zaznaczZmianeGracza(true);
        zmienCzas("00:00:00", true);
        zmienCzas("00:00:00", false);
        menuZegar(false);
        menuPoddajeSie(true);
        repaint();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jKolor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private program.Szachownica szachownica1;
    // End of variables declaration//GEN-END:variables
}
