package program;
import javax.swing.ImageIcon;
import java.awt.Component;
import java.awt.Graphics;

public class OProgramie extends javax.swing.JDialog {
    private ImageIcon tlo;
    
    /** Creates new form OProgramie */
    public OProgramie(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        tlo = new ImageIcon(getClass().getResource("/inne/oprog.gif"));
        initComponents();
        setSize(250,190); 
        setLocationRelativeTo(parent);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        getContentPane().setLayout(null);

        setTitle("O programie");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jButton1.setMnemonic('z');
        jButton1.setText("Ok");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        getContentPane().add(jButton1);
        jButton1.setBounds(50, 60, 79, 26);

        jLabel1.setForeground(new java.awt.Color(102, 255, 0));
        jLabel1.setText("Programowanie w Unix");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 10, 150, 16);

        jLabel2.setForeground(new java.awt.Color(51, 255, 0));
        jLabel2.setText("Damian Dr\u0105gowski");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 30, 160, 16);

        pack();
    }//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        closeDialog(null);
    }//GEN-LAST:event_jButton1ActionPerformed
    
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    public void paint(java.awt.Graphics graphics) {
        tlo.paintIcon(this, graphics, 0, 0);
        
        Component skladowe[] = getContentPane().getComponents();
        for (int i=0; i<skladowe.length; i++) {
            Graphics g = skladowe[i].getGraphics();
            skladowe[i].paint(g);
        }
    }    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
    
}
